image: ruby:2.1

before_script:
  - apt-get update -y
  - apt-get install php5 -y
  - sed -i -- 's/;phar.readonly = On/phar.readonly = Off/g' /etc/php5/cli/php.ini

stages:
  - build
  - test

job1:
  stage: build
  script:
    - php build-tools/phar.php

job2:
  stage: test
  script:
    - php build-tools/phar.php
    - test/test.sh