image: eriksencosta/php-dev

stages:
  - test
  - build

test:5.3:
  stage: test
  script:
    - . build-tools/prepare-env.sh 5.3
    - phpunit --bootstrap src/index.php --no-configuration /home/sven/bitsensor-plugins/php/test

test:5.4:
  stage: test
  script:
    - . build-tools/prepare-env.sh 5.4
    - phpunit --bootstrap src/index.php --no-configuration /home/sven/bitsensor-plugins/php/test

test:5.5:
  stage: test
  script:
    - . build-tools/prepare-env.sh 5.5
    - phpunit --bootstrap src/index.php --no-configuration /home/sven/bitsensor-plugins/php/test

test:5.6:
  stage: test
  script:
    - . build-tools/prepare-env.sh 5.6
    - phpunit --bootstrap src/index.php --no-configuration /home/sven/bitsensor-plugins/php/test

build:
  stage: build
  script:
    - . build-tools/prepare-env.sh 5.6
    - php build-tools/phar.php
  only:
    - master
    - develop
  artifacts:
      paths:
        - target