image: eriksencosta/php-dev

# Test template
.test_template: &test_job
  stage: test
  image: miya0001/phpenv:$PHP_VERSION
  script:
    - . build-tools/prepare-env.sh
    - composer config cache-files-dir .composercache
    - vendor/bin/phpunit --bootstrap vendor/autoload.php --no-configuration test/

cache:
  paths:
  - .composercache

stages:
  - test
  - build
  - deploy

test:5.5:
  <<: *test_job
  variables:
    PHP_VERSION: '5.5'
test:5.6:
  <<: *test_job
  variables:
    PHP_VERSION: '5.6'
test:7.0:
  <<: *test_job
  variables:
    PHP_VERSION: '7.0'
test:7.1:
  <<: *test_job
  variables:
    PHP_VERSION: '7.1'

build:
  stage: build
  before_script:
    - composer config cache-files-dir .composercache
  script:
    - . build-tools/prepare-env.sh 5.6
    - php build-tools/phar.php
  only:
    - master
    - develop
    - tags
  artifacts:
    paths:
      - target
    expire_in: 20m

deploy:packagist:
  stage: deploy
  script:
    - curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username='$PACKAGIST_USERNAME'&apiToken='$PACKAGIST_API_KEY -d'{"repository":{"url":"'$PACKAGIST_URL'"}}'
  only:
    - master
    - develop
    - tags

pages:
  image: node:8.9.0
  before_script:
    - npm install gitbook-cli -g -q # install gitbook
    - gitbook fetch latest # fetch latest stable version
  script:
    - gitbook build . public
  artifacts:
    paths:
      - public
    expire_in: 15m
  only:
    - master
