image: phpunit/phpunit:5.0.3

before_script:
  - sed -i -- 's/;phar.readonly = On/phar.readonly = Off/g' /etc/php5/cli/php.ini

stages:
  - build
  - test

build:
  stage: build
  script:
    - php build-tools/phar.php

test:
  stage: test
  script:
    - php build-tools/phar.php
    - test/test.sh