image: eriksencosta/php-dev

stages:
  - test
  - build
  - deploy

test:5.3:
  stage: test
  script:
    - . build-tools/prepare-env.sh 5.3
    - phpunit --bootstrap src/index.php --no-configuration test/

test:5.4:
  stage: test
  script:
    - . build-tools/prepare-env.sh 5.4
    - phpunit --bootstrap src/index.php --no-configuration test/

test:5.5:
  stage: test
  script:
    - . build-tools/prepare-env.sh 5.5
    - phpunit --bootstrap src/index.php --no-configuration test/

test:5.6:
  stage: test
  script:
    - . build-tools/prepare-env.sh 5.6
    - phpunit --bootstrap src/index.php --no-configuration test/

build:
  stage: build
  script:
    - . build-tools/prepare-env.sh 5.6
    - php build-tools/phar.php
  only:
    - master
    - develop
    - tags
  artifacts:
      paths:
        - target

deploy:packagist:
  stage: deploy
  script:
    - curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username='$PACKAGIST_USERNAME'&apiToken='$PACKAGIST_API_KEY -d'{"repository":{"url":"'$PACKAGIST_URL'"}}'
  only:
    - master
    - develop
    - tags