<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invocation.proto

namespace Proto\Invocation\SQLInvocation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Invocation.SQLInvocation.Query</code>
 */
class Query extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string query = 1;</code>
     */
    private $query = '';
    /**
     * Generated from protobuf field <code>repeated string tables = 3;</code>
     */
    private $tables;
    /**
     * Generated from protobuf field <code>map<string, string> parameter = 2;</code>
     */
    private $parameter;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $query
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tables
     *     @type array|\Google\Protobuf\Internal\MapField $parameter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invocation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string query = 1;</code>
     * @return string
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * Generated from protobuf field <code>string query = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string tables = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTables()
    {
        return $this->tables;
    }

    /**
     * Generated from protobuf field <code>repeated string tables = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTables($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tables = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> parameter = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getParameter()
    {
        return $this->parameter;
    }

    /**
     * Generated from protobuf field <code>map<string, string> parameter = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setParameter($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->parameter = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Query::class, \Proto\Invocation_SQLInvocation_Query::class);

