<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataLeakage.proto

namespace GPBMetadata;

class DataLeakage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Detection::initOnce();
        \GPBMetadata\Invocation::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7010a11446174614c65616b6167652e70726f746f120570726f746f1a" .
            "10496e766f636174696f6e2e70726f746f225a0a0b446174614c65616b61" .
            "676512240a0a646574656374696f6e7318012003280b32102e70726f746f" .
            "2e446574656374696f6e12250a0a696e766f636174696f6e18022001280b" .
            "32112e70726f746f2e496e766f636174696f6e42210a1d696f2e62697473" .
            "656e736f722e6c69622e656e746974792e70726f746f5001500050016206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

