<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Error.proto

namespace GPBMetadata;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\GeneratedBy::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae4010a0b4572726f722e70726f746f120570726f746f22a0010a054572" .
            "726f72120c0a04636f646518012001280512130a0b646573637269707469" .
            "6f6e18022001280912100a086c6f636174696f6e180320012809120c0a04" .
            "6c696e65180420012805120c0a047479706518052001280912270a0b6765" .
            "6e657261746564627918062001280e32122e70726f746f2e47656e657261" .
            "7465644279120c0a0468617368180720012803120f0a07636f6e74657874" .
            "18082003280942210a1d696f2e62697473656e736f722e6c69622e656e74" .
            "6974792e70726f746f50015000620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

