<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Error.proto

namespace GPBMetadata;

class Error
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        \GPBMetadata\GeneratedBy::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af7010a0b4572726f722e70726f746f120570726f746f1a1147656e6572" .
            "6174656442792e70726f746f22a0010a054572726f72120c0a04636f6465" .
            "18012001280512130a0b6465736372697074696f6e18022001280912100a" .
            "086c6f636174696f6e180320012809120c0a046c696e6518042001280512" .
            "0c0a047479706518052001280912270a0b67656e65726174656462791806" .
            "2001280e32122e70726f746f2e47656e6572617465644279120c0a046861" .
            "7368180720012803120f0a07636f6e7465787418082003280942210a1d69" .
            "6f2e62697473656e736f722e6c69622e656e746974792e70726f746f5001" .
            "5000620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

