<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GeneratedBy.proto

namespace GPBMetadata;

class GeneratedBy
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7f0a1147656e65726174656442792e70726f746f120570726f746f2a38" .
            "0a0b47656e6572617465644279120c0a08424954425241494e1000120a0a" .
            "06504c5547494e1001120f0a0b4d4f445345435552495459100242210a1d" .
            "696f2e62697473656e736f722e6c69622e656e746974792e70726f746f50" .
            "01620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

