<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Grade.proto

namespace GPBMetadata;

class Grade
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a720a0b47726164652e70726f746f120570726f746f2a310a0547726164" .
            "6512050a0141100012050a0142100112050a0143100212050a0144100312" .
            "050a0145100412050a0146100542210a1d696f2e62697473656e736f722e" .
            "6c69622e656e746974792e70726f746f5001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

