<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto\Detection;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Detection.ApplicableTo</code>
 */
class ApplicableTo extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of application, ie. drupal
     *
     * Generated from protobuf field <code>repeated string application = 7;</code>
     */
    private $application;
    /**
     * Language of application, ie. php, java
     *
     * Generated from protobuf field <code>repeated string language = 8;</code>
     */
    private $language;
    /**
     * Platform, ie. Windows/Linux
     *
     * Generated from protobuf field <code>repeated string platform = 9;</code>
     */
    private $platform;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $application
     *           Name of application, ie. drupal
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $language
     *           Language of application, ie. php, java
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $platform
     *           Platform, ie. Windows/Linux
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Detection::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of application, ie. drupal
     *
     * Generated from protobuf field <code>repeated string application = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApplication()
    {
        return $this->application;
    }

    /**
     * Name of application, ie. drupal
     *
     * Generated from protobuf field <code>repeated string application = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApplication($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->application = $arr;

        return $this;
    }

    /**
     * Language of application, ie. php, java
     *
     * Generated from protobuf field <code>repeated string language = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Language of application, ie. php, java
     *
     * Generated from protobuf field <code>repeated string language = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLanguage($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->language = $arr;

        return $this;
    }

    /**
     * Platform, ie. Windows/Linux
     *
     * Generated from protobuf field <code>repeated string platform = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * Platform, ie. Windows/Linux
     *
     * Generated from protobuf field <code>repeated string platform = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlatform($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->platform = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ApplicableTo::class, \Proto\Detection_ApplicableTo::class);

