<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto\Detection;

/**
 * sorted from 'worse' to more benign
 *
 * Protobuf type <code>proto.Detection.Reason</code>
 */
class Reason
{
    /**
     * low-false-positive generic attack pattern.
     *
     * Generated from protobuf enum <code>KNOWN_ATTACK = 0;</code>
     */
    const KNOWN_ATTACK = 0;
    /**
     * Note: this reason is not worse than CVE but first enum value must be 0
     *
     * Generated from protobuf enum <code>CVE = 3;</code>
     */
    const CVE = 3;
    /**
     * pentest or scanner tool
     *
     * Generated from protobuf enum <code>TOOL = 2;</code>
     */
    const TOOL = 2;
    /**
     * possibly-false-positive generic pattern
     *
     * Generated from protobuf enum <code>HEURISTIC = 4;</code>
     */
    const HEURISTIC = 4;
    /**
     * suspicious source / session / user
     *
     * Generated from protobuf enum <code>REPUTATION = 5;</code>
     */
    const REPUTATION = 5;
    /**
     * temporal or other unusual signals
     *
     * Generated from protobuf enum <code>BEHAVIOUR = 1;</code>
     */
    const BEHAVIOUR = 1;
    /**
     * invalid HTTP, unparseable XML/SOAP/JSON
     *
     * Generated from protobuf enum <code>PROTOCOL_VIOLATION = 6;</code>
     */
    const PROTOCOL_VIOLATION = 6;
    /**
     * informational logging of request
     *
     * Generated from protobuf enum <code>INFORMATIONAL = 7;</code>
     */
    const INFORMATIONAL = 7;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Reason::class, \Proto\Detection_Reason::class);

