<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto\Detection;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Detection.StandardsMapping</code>
 */
class StandardsMapping extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string crs = 1;</code>
     */
    private $crs;
    /**
     * Generated from protobuf field <code>repeated string wasctc = 2;</code>
     */
    private $wasctc;
    /**
     * Generated from protobuf field <code>repeated string owasp = 3;</code>
     */
    private $owasp;
    /**
     * Generated from protobuf field <code>repeated string pci = 4;</code>
     */
    private $pci;
    /**
     * Generated from protobuf field <code>repeated string appsensor = 5;</code>
     */
    private $appsensor;
    /**
     * Generated from protobuf field <code>repeated string cve = 6;</code>
     */
    private $cve;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $crs
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $wasctc
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $owasp
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $pci
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $appsensor
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $cve
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Detection::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string crs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCrs()
    {
        return $this->crs;
    }

    /**
     * Generated from protobuf field <code>repeated string crs = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCrs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->crs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string wasctc = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWasctc()
    {
        return $this->wasctc;
    }

    /**
     * Generated from protobuf field <code>repeated string wasctc = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWasctc($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->wasctc = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string owasp = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOwasp()
    {
        return $this->owasp;
    }

    /**
     * Generated from protobuf field <code>repeated string owasp = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOwasp($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->owasp = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string pci = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPci()
    {
        return $this->pci;
    }

    /**
     * Generated from protobuf field <code>repeated string pci = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPci($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->pci = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string appsensor = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAppsensor()
    {
        return $this->appsensor;
    }

    /**
     * Generated from protobuf field <code>repeated string appsensor = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAppsensor($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->appsensor = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string cve = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCve()
    {
        return $this->cve;
    }

    /**
     * Generated from protobuf field <code>repeated string cve = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCve($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->cve = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StandardsMapping::class, \Proto\Detection_StandardsMapping::class);

