<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Datapoint.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Agent\Type instead.
     * @deprecated
     */
    class Agent_Type {}
}
class_exists(Agent\Type::class);
@trigger_error('Proto\Agent_Type is deprecated and will be removed in the next major release. Use Proto\Agent\Type instead', E_USER_DEPRECATED);

