<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Block.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Block</code>
 */
class Block extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>bool active = 2;</code>
     */
    private $active = false;
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>string createdBy = 4;</code>
     */
    private $createdBy = '';
    /**
     * Generated from protobuf field <code>int64 creationDate = 5;</code>
     */
    private $creationDate = 0;
    /**
     * Generated from protobuf field <code>int64 updateDate = 6;</code>
     */
    private $updateDate = 0;
    /**
     * Generated from protobuf field <code>repeated .proto.Datapoint datapoints = 7;</code>
     */
    private $datapoints;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type bool $active
     *     @type string $description
     *     @type string $createdBy
     *     @type int|string $creationDate
     *     @type int|string $updateDate
     *     @type \Proto\Datapoint[]|\Google\Protobuf\Internal\RepeatedField $datapoints
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool active = 2;</code>
     * @return bool
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Generated from protobuf field <code>bool active = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setActive($var)
    {
        GPBUtil::checkBool($var);
        $this->active = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string createdBy = 4;</code>
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * Generated from protobuf field <code>string createdBy = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->createdBy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 creationDate = 5;</code>
     * @return int|string
     */
    public function getCreationDate()
    {
        return $this->creationDate;
    }

    /**
     * Generated from protobuf field <code>int64 creationDate = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreationDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->creationDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 updateDate = 6;</code>
     * @return int|string
     */
    public function getUpdateDate()
    {
        return $this->updateDate;
    }

    /**
     * Generated from protobuf field <code>int64 updateDate = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdateDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->updateDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Datapoint datapoints = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDatapoints()
    {
        return $this->datapoints;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Datapoint datapoints = 7;</code>
     * @param \Proto\Datapoint[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDatapoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Datapoint::class);
        $this->datapoints = $arr;

        return $this;
    }

}

