<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Datapoint.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Datapoint</code>
 */
class Datapoint extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, string> context = 1;</code>
     */
    private $context;
    /**
     * Generated from protobuf field <code>repeated .proto.Error errors = 2;</code>
     */
    private $errors;
    /**
     * Generated from protobuf field <code>map<string, string> endpoint = 3;</code>
     */
    private $endpoint;
    /**
     * Generated from protobuf field <code>map<string, string> meta = 4;</code>
     */
    private $meta;
    /**
     * Generated from protobuf field <code>repeated .proto.Detection detections = 5;</code>
     */
    private $detections;
    /**
     * Generated from protobuf field <code>map<string, string> input = 6;</code>
     */
    private $input;
    /**
     * Generated from protobuf field <code>.proto.Invocation invocation = 7;</code>
     */
    private $invocation = null;
    /**
     * Generated from protobuf field <code>repeated .proto.Vulnerability vulnerabilities = 9;</code>
     */
    private $vulnerabilities;
    /**
     * Generated from protobuf field <code>repeated .proto.DataLeakage data_leakages = 10;</code>
     */
    private $data_leakages;
    /**
     * key should not contain dot .
     *
     * Generated from protobuf field <code>map<string, .proto.PersonalData> personal_data = 11;</code>
     */
    private $personal_data;
    /**
     * Generated from protobuf field <code>.proto.Agent agent = 12;</code>
     */
    private $agent = null;
    /**
     * Generated from protobuf field <code>.proto.Notable notable = 13;</code>
     */
    private $notable = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $context
     *     @type \Proto\Error[]|\Google\Protobuf\Internal\RepeatedField $errors
     *     @type array|\Google\Protobuf\Internal\MapField $endpoint
     *     @type array|\Google\Protobuf\Internal\MapField $meta
     *     @type \Proto\Detection[]|\Google\Protobuf\Internal\RepeatedField $detections
     *     @type array|\Google\Protobuf\Internal\MapField $input
     *     @type \Proto\Invocation $invocation
     *     @type \Proto\Vulnerability[]|\Google\Protobuf\Internal\RepeatedField $vulnerabilities
     *     @type \Proto\DataLeakage[]|\Google\Protobuf\Internal\RepeatedField $data_leakages
     *     @type array|\Google\Protobuf\Internal\MapField $personal_data
     *           key should not contain dot .
     *     @type \Proto\Agent $agent
     *     @type \Proto\Notable $notable
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Datapoint::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, string> context = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>map<string, string> context = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setContext($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->context = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Error errors = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Error errors = 2;</code>
     * @param \Proto\Error[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Error::class);
        $this->errors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> endpoint = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Generated from protobuf field <code>map<string, string> endpoint = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setEndpoint($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->endpoint = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> meta = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> meta = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->meta = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Detection detections = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetections()
    {
        return $this->detections;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Detection detections = 5;</code>
     * @param \Proto\Detection[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetections($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Detection::class);
        $this->detections = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> input = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * Generated from protobuf field <code>map<string, string> input = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setInput($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->input = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Invocation invocation = 7;</code>
     * @return \Proto\Invocation
     */
    public function getInvocation()
    {
        return $this->invocation;
    }

    /**
     * Generated from protobuf field <code>.proto.Invocation invocation = 7;</code>
     * @param \Proto\Invocation $var
     * @return $this
     */
    public function setInvocation($var)
    {
        GPBUtil::checkMessage($var, \Proto\Invocation::class);
        $this->invocation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Vulnerability vulnerabilities = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVulnerabilities()
    {
        return $this->vulnerabilities;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Vulnerability vulnerabilities = 9;</code>
     * @param \Proto\Vulnerability[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVulnerabilities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Vulnerability::class);
        $this->vulnerabilities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.DataLeakage data_leakages = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDataLeakages()
    {
        return $this->data_leakages;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.DataLeakage data_leakages = 10;</code>
     * @param \Proto\DataLeakage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDataLeakages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\DataLeakage::class);
        $this->data_leakages = $arr;

        return $this;
    }

    /**
     * key should not contain dot .
     *
     * Generated from protobuf field <code>map<string, .proto.PersonalData> personal_data = 11;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPersonalData()
    {
        return $this->personal_data;
    }

    /**
     * key should not contain dot .
     *
     * Generated from protobuf field <code>map<string, .proto.PersonalData> personal_data = 11;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPersonalData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\PersonalData::class);
        $this->personal_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Agent agent = 12;</code>
     * @return \Proto\Agent
     */
    public function getAgent()
    {
        return $this->agent;
    }

    /**
     * Generated from protobuf field <code>.proto.Agent agent = 12;</code>
     * @param \Proto\Agent $var
     * @return $this
     */
    public function setAgent($var)
    {
        GPBUtil::checkMessage($var, \Proto\Agent::class);
        $this->agent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Notable notable = 13;</code>
     * @return \Proto\Notable
     */
    public function getNotable()
    {
        return $this->notable;
    }

    /**
     * Generated from protobuf field <code>.proto.Notable notable = 13;</code>
     * @param \Proto\Notable $var
     * @return $this
     */
    public function setNotable($var)
    {
        GPBUtil::checkMessage($var, \Proto\Notable::class);
        $this->notable = $var;

        return $this;
    }

}

