<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataLeakage.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.DataLeakage</code>
 */
class DataLeakage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.Detection detections = 1;</code>
     */
    private $detections;
    /**
     * Generated from protobuf field <code>.proto.Invocation invocation = 2;</code>
     */
    private $invocation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Detection[]|\Google\Protobuf\Internal\RepeatedField $detections
     *     @type \Proto\Invocation $invocation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DataLeakage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Detection detections = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetections()
    {
        return $this->detections;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Detection detections = 1;</code>
     * @param \Proto\Detection[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetections($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Detection::class);
        $this->detections = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Invocation invocation = 2;</code>
     * @return \Proto\Invocation
     */
    public function getInvocation()
    {
        return $this->invocation;
    }

    /**
     * Generated from protobuf field <code>.proto.Invocation invocation = 2;</code>
     * @param \Proto\Invocation $var
     * @return $this
     */
    public function setInvocation($var)
    {
        GPBUtil::checkMessage($var, \Proto\Invocation::class);
        $this->invocation = $var;

        return $this;
    }

}

