<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Datapoint.proto

namespace Proto;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>proto.Datapoint</code>
 */
class Datapoint extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>map&lt;string, string&gt; context = 1;</code>
     */
    private $context;
    /**
     * <code>repeated .proto.Error errors = 2;</code>
     */
    private $errors;
    /**
     * <code>map&lt;string, string&gt; endpoint = 3;</code>
     */
    private $endpoint;
    /**
     * <code>map&lt;string, string&gt; meta = 4;</code>
     */
    private $meta;
    /**
     * <code>repeated .proto.Detection detections = 5;</code>
     */
    private $detections;
    /**
     * <code>map&lt;string, string&gt; input = 6;</code>
     */
    private $input;
    /**
     * <code>.proto.Invocation invocation = 7;</code>
     */
    private $invocation = null;

    public function __construct()
    {
        \GPBMetadata\Datapoint::initOnce();
        parent::__construct();
    }

    /**
     * <code>map&lt;string, string&gt; context = 1;</code>
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * <code>map&lt;string, string&gt; context = 1;</code>
     */
    public function setContext(&$var)
    {
        $this->context = $var;
    }

    /**
     * <code>repeated .proto.Error errors = 2;</code>
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * <code>repeated .proto.Error errors = 2;</code>
     */
    public function setErrors(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Error::class);
        $this->errors = $var;
    }

    /**
     * <code>map&lt;string, string&gt; endpoint = 3;</code>
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * <code>map&lt;string, string&gt; endpoint = 3;</code>
     */
    public function setEndpoint(&$var)
    {
        $this->endpoint = $var;
    }

    /**
     * <code>map&lt;string, string&gt; meta = 4;</code>
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * <code>map&lt;string, string&gt; meta = 4;</code>
     */
    public function setMeta(&$var)
    {
        $this->meta = $var;
    }

    /**
     * <code>repeated .proto.Detection detections = 5;</code>
     */
    public function getDetections()
    {
        return $this->detections;
    }

    /**
     * <code>repeated .proto.Detection detections = 5;</code>
     */
    public function setDetections(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Detection::class);
        $this->detections = $var;
    }

    /**
     * <code>map&lt;string, string&gt; input = 6;</code>
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * <code>map&lt;string, string&gt; input = 6;</code>
     */
    public function setInput(&$var)
    {
        $this->input = $var;
    }

    /**
     * <code>.proto.Invocation invocation = 7;</code>
     */
    public function getInvocation()
    {
        return $this->invocation;
    }

    /**
     * <code>.proto.Invocation invocation = 7;</code>
     */
    public function setInvocation(&$var)
    {
        GPBUtil::checkMessage($var, \Proto\Invocation::class);
        $this->invocation = $var;
    }

}

