<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Detection\VendorImplementation\F5 instead.
     * @deprecated
     */
    class Detection_VendorImplementation_F5 {}
}
class_exists(Detection\VendorImplementation\F5::class);
@trigger_error('Proto\Detection_VendorImplementation_F5 is deprecated and will be removed in the next major release. Use Proto\Detection\VendorImplementation\F5 instead', E_USER_DEPRECATED);

