<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Detection\ApplicableTo instead.
     * @deprecated
     */
    class Detection_ApplicableTo {}
}
class_exists(Detection\ApplicableTo::class);
@trigger_error('Proto\Detection_ApplicableTo is deprecated and will be removed in the next major release. Use Proto\Detection\ApplicableTo instead', E_USER_DEPRECATED);

