<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Detection\Attack instead.
     * @deprecated
     */
    class Detection_Attack {}
}
class_exists(Detection\Attack::class);
@trigger_error('Proto\Detection_Attack is deprecated and will be removed in the next major release. Use Proto\Detection\Attack instead', E_USER_DEPRECATED);

