<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>proto.Detection</code>
 */
class Detection extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string ids = 1;</code>
     */
    private $ids = '';
    /**
     * <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * <code>string description = 3;</code>
     */
    private $description = '';
    /**
     * <code>repeated string type = 4;</code>
     */
    private $type;
    /**
     * <code>float severity = 5;</code>
     */
    private $severity = 0.0;
    /**
     * <code>float certainty = 6;</code>
     */
    private $certainty = 0.0;
    /**
     * <code>bool successful = 7;</code>
     */
    private $successful = false;
    /**
     * <code>bool relevant = 8;</code>
     */
    private $relevant = false;
    /**
     * <code>.proto.Detection.Reason reason = 9;</code>
     */
    private $reason = 0;
    /**
     * <code>.proto.GeneratedBy generatedby = 10;</code>
     */
    private $generatedby = 0;
    /**
     * <code>bool attack = 11;</code>
     */
    private $attack = false;
    /**
     * <code>repeated string input = 12;</code>
     */
    private $input;
    /**
     * <code>repeated string errors = 13;</code>
     */
    private $errors;
    /**
     * <code>int64 hash = 14;</code>
     */
    private $hash = 0;
    /**
     * <code>int64 ruleHash = 15;</code>
     */
    private $ruleHash = 0;
    /**
     * <code>string onKey = 16;</code>
     */
    private $onKey = '';
    /**
     * <code>string byInput = 17;</code>
     */
    private $byInput = '';
    /**
     * <code>repeated string tags = 18;</code>
     */
    private $tags;

    public function __construct()
    {
        \GPBMetadata\Detection::initOnce();
        parent::__construct();
    }

    /**
     * <code>string ids = 1;</code>
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * <code>string ids = 1;</code>
     */
    public function setIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->ids = $var;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>string description = 3;</code>
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * <code>string description = 3;</code>
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

    /**
     * <code>repeated string type = 4;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>repeated string type = 4;</code>
     */
    public function setType(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->type = $var;
    }

    /**
     * <code>float severity = 5;</code>
     */
    public function getSeverity()
    {
        return $this->severity;
    }

    /**
     * <code>float severity = 5;</code>
     */
    public function setSeverity($var)
    {
        GPBUtil::checkFloat($var);
        $this->severity = $var;
    }

    /**
     * <code>float certainty = 6;</code>
     */
    public function getCertainty()
    {
        return $this->certainty;
    }

    /**
     * <code>float certainty = 6;</code>
     */
    public function setCertainty($var)
    {
        GPBUtil::checkFloat($var);
        $this->certainty = $var;
    }

    /**
     * <code>bool successful = 7;</code>
     */
    public function getSuccessful()
    {
        return $this->successful;
    }

    /**
     * <code>bool successful = 7;</code>
     */
    public function setSuccessful($var)
    {
        GPBUtil::checkBool($var);
        $this->successful = $var;
    }

    /**
     * <code>bool relevant = 8;</code>
     */
    public function getRelevant()
    {
        return $this->relevant;
    }

    /**
     * <code>bool relevant = 8;</code>
     */
    public function setRelevant($var)
    {
        GPBUtil::checkBool($var);
        $this->relevant = $var;
    }

    /**
     * <code>.proto.Detection.Reason reason = 9;</code>
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * <code>.proto.Detection.Reason reason = 9;</code>
     */
    public function setReason($var)
    {
        GPBUtil::checkEnum($var, \Proto\Detection_Reason::class);
        $this->reason = $var;
    }

    /**
     * <code>.proto.GeneratedBy generatedby = 10;</code>
     */
    public function getGeneratedby()
    {
        return $this->generatedby;
    }

    /**
     * <code>.proto.GeneratedBy generatedby = 10;</code>
     */
    public function setGeneratedby($var)
    {
        GPBUtil::checkEnum($var, \Proto\GeneratedBy::class);
        $this->generatedby = $var;
    }

    /**
     * <code>bool attack = 11;</code>
     */
    public function getAttack()
    {
        return $this->attack;
    }

    /**
     * <code>bool attack = 11;</code>
     */
    public function setAttack($var)
    {
        GPBUtil::checkBool($var);
        $this->attack = $var;
    }

    /**
     * <code>repeated string input = 12;</code>
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * <code>repeated string input = 12;</code>
     */
    public function setInput(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->input = $var;
    }

    /**
     * <code>repeated string errors = 13;</code>
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * <code>repeated string errors = 13;</code>
     */
    public function setErrors(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->errors = $var;
    }

    /**
     * <code>int64 hash = 14;</code>
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * <code>int64 hash = 14;</code>
     */
    public function setHash($var)
    {
        GPBUtil::checkInt64($var);
        $this->hash = $var;
    }

    /**
     * <code>int64 ruleHash = 15;</code>
     */
    public function getRuleHash()
    {
        return $this->ruleHash;
    }

    /**
     * <code>int64 ruleHash = 15;</code>
     */
    public function setRuleHash($var)
    {
        GPBUtil::checkInt64($var);
        $this->ruleHash = $var;
    }

    /**
     * <code>string onKey = 16;</code>
     */
    public function getOnKey()
    {
        return $this->onKey;
    }

    /**
     * <code>string onKey = 16;</code>
     */
    public function setOnKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->onKey = $var;
    }

    /**
     * <code>string byInput = 17;</code>
     */
    public function getByInput()
    {
        return $this->byInput;
    }

    /**
     * <code>string byInput = 17;</code>
     */
    public function setByInput($var)
    {
        GPBUtil::checkString($var, True);
        $this->byInput = $var;
    }

    /**
     * <code>repeated string tags = 18;</code>
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * <code>repeated string tags = 18;</code>
     */
    public function setTags(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $var;
    }

}

