<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Detection\Rule instead.
     * @deprecated
     */
    class Detection_Rule {}
}
class_exists(Detection\Rule::class);
@trigger_error('Proto\Detection_Rule is deprecated and will be removed in the next major release. Use Proto\Detection\Rule instead', E_USER_DEPRECATED);

