<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Detection\Reason instead.
     * @deprecated
     */
    class Detection_Reason {}
}
class_exists(Detection\Reason::class);
@trigger_error('Proto\Detection_Reason is deprecated and will be removed in the next major release. Use Proto\Detection\Reason instead', E_USER_DEPRECATED);

