<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Detection\VendorImplementation instead.
     * @deprecated
     */
    class Detection_VendorImplementation {}
}
class_exists(Detection\VendorImplementation::class);
@trigger_error('Proto\Detection_VendorImplementation is deprecated and will be removed in the next major release. Use Proto\Detection\VendorImplementation instead', E_USER_DEPRECATED);

