<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Detection\VendorImplementation\Incapsula instead.
     * @deprecated
     */
    class Detection_VendorImplementation_Incapsula {}
}
class_exists(Detection\VendorImplementation\Incapsula::class);
@trigger_error('Proto\Detection_VendorImplementation_Incapsula is deprecated and will be removed in the next major release. Use Proto\Detection\VendorImplementation\Incapsula instead', E_USER_DEPRECATED);

