<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Detection\StandardsMapping instead.
     * @deprecated
     */
    class Detection_StandardsMapping {}
}
class_exists(Detection\StandardsMapping::class);
@trigger_error('Proto\Detection_StandardsMapping is deprecated and will be removed in the next major release. Use Proto\Detection\StandardsMapping instead', E_USER_DEPRECATED);

