<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Detection.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Detection\VendorImplementation\CoreRuleSet instead.
     * @deprecated
     */
    class Detection_VendorImplementation_CoreRuleSet {}
}
class_exists(Detection\VendorImplementation\CoreRuleSet::class);
@trigger_error('Proto\Detection_VendorImplementation_CoreRuleSet is deprecated and will be removed in the next major release. Use Proto\Detection\VendorImplementation\CoreRuleSet instead', E_USER_DEPRECATED);

