<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GeneratedBy.proto

namespace Proto;

/**
 * Protobuf enum <code>proto.GeneratedBy</code>
 */
class GeneratedBy
{
    /**
     * <code>BITBRAIN = 0;</code>
     */
    const BITBRAIN = 0;
    /**
     * <code>PLUGIN = 1;</code>
     */
    const PLUGIN = 1;
}

