<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GeneratedBy.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\GeneratedBy</code>
 */
class GeneratedBy
{
    /**
     * Generated from protobuf enum <code>BITBRAIN = 0;</code>
     */
    const BITBRAIN = 0;
    /**
     * Generated from protobuf enum <code>PLUGIN = 1;</code>
     */
    const PLUGIN = 1;
    /**
     * Generated from protobuf enum <code>MODSECURITY = 2;</code>
     */
    const MODSECURITY = 2;
}

