<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Grade.proto

namespace Proto;

/**
 * Protobuf type <code>proto.Grade</code>
 */
class Grade
{
    /**
     * green: noise
     *
     * Generated from protobuf enum <code>A = 0;</code>
     */
    const A = 0;
    /**
     * Generated from protobuf enum <code>B = 1;</code>
     */
    const B = 1;
    /**
     * Generated from protobuf enum <code>C = 2;</code>
     */
    const C = 2;
    /**
     * bad
     *
     * Generated from protobuf enum <code>D = 3;</code>
     */
    const D = 3;
    /**
     * worse
     *
     * Generated from protobuf enum <code>E = 4;</code>
     */
    const E = 4;
    /**
     * red: worst situation ever
     *
     * Generated from protobuf enum <code>F = 5;</code>
     */
    const F = 5;
}

