<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invocation.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Invocation\SQLInvocation instead.
     * @deprecated
     */
    class Invocation_SQLInvocation {}
}
class_exists(Invocation\SQLInvocation::class);
@trigger_error('Proto\Invocation_SQLInvocation is deprecated and will be removed in the next major release. Use Proto\Invocation\SQLInvocation instead', E_USER_DEPRECATED);

