<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invocation.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Invocation</code>
 */
class Invocation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.Invocation.SQLInvocation sql_invocations = 1;</code>
     */
    private $sql_invocations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Invocation\SQLInvocation[]|\Google\Protobuf\Internal\RepeatedField $sql_invocations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invocation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Invocation.SQLInvocation sql_invocations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSqlInvocations()
    {
        return $this->sql_invocations;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Invocation.SQLInvocation sql_invocations = 1;</code>
     * @param \Proto\Invocation\SQLInvocation[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSqlInvocations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Invocation\SQLInvocation::class);
        $this->sql_invocations = $arr;

        return $this;
    }

}

