<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invocation.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SQL Invocation
 *
 * Generated from protobuf message <code>proto.Invocation.SQLInvocation</code>
 */
class Invocation_SQLInvocation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.Invocation.SQLInvocation.Query queries = 1;</code>
     */
    private $queries;
    /**
     * Generated from protobuf field <code>map<string, string> endpoint = 2;</code>
     */
    private $endpoint;
    /**
     * Generated from protobuf field <code>string prepare_statement = 3;</code>
     */
    private $prepare_statement = '';
    /**
     * Generated from protobuf field <code>string prepare_call = 4;</code>
     */
    private $prepare_call = '';

    public function __construct() {
        \GPBMetadata\Invocation::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Invocation.SQLInvocation.Query queries = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getQueries()
    {
        return $this->queries;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Invocation.SQLInvocation.Query queries = 1;</code>
     * @param \Proto\Invocation_SQLInvocation_Query[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setQueries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Invocation_SQLInvocation_Query::class);
        $this->queries = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> endpoint = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Generated from protobuf field <code>map<string, string> endpoint = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setEndpoint($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->endpoint = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prepare_statement = 3;</code>
     * @return string
     */
    public function getPrepareStatement()
    {
        return $this->prepare_statement;
    }

    /**
     * Generated from protobuf field <code>string prepare_statement = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrepareStatement($var)
    {
        GPBUtil::checkString($var, True);
        $this->prepare_statement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prepare_call = 4;</code>
     * @return string
     */
    public function getPrepareCall()
    {
        return $this->prepare_call;
    }

    /**
     * Generated from protobuf field <code>string prepare_call = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPrepareCall($var)
    {
        GPBUtil::checkString($var, True);
        $this->prepare_call = $var;

        return $this;
    }

}

