<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invocation.proto

namespace Proto;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>proto.Invocation</code>
 */
class Invocation extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .proto.Invocation.SQLInvocation sqlInvocations = 1;</code>
     */
    private $sqlInvocations;

    public function __construct()
    {
        \GPBMetadata\Invocation::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .proto.Invocation.SQLInvocation sqlInvocations = 1;</code>
     */
    public function getSqlInvocations()
    {
        return $this->sqlInvocations;
    }

    /**
     * <code>repeated .proto.Invocation.SQLInvocation sqlInvocations = 1;</code>
     */
    public function setSqlInvocations(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Invocation_SQLInvocation::class);
        $this->sqlInvocations = $var;
    }

}

