<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invocation.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Invocation\SQLInvocation\Query instead.
     * @deprecated
     */
    class Invocation_SQLInvocation_Query {}
}
class_exists(Invocation\SQLInvocation\Query::class);
@trigger_error('Proto\Invocation_SQLInvocation_Query is deprecated and will be removed in the next major release. Use Proto\Invocation\SQLInvocation\Query instead', E_USER_DEPRECATED);

