<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Datapoint.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Notable</code>
 */
class Notable extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string explanation = 1;</code>
     */
    private $explanation = '';
    /**
     * combined severity of all the DP's detections, with maybe some magic
     *
     * Generated from protobuf field <code>.proto.Grade grade = 2;</code>
     */
    private $grade = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $explanation
     *     @type int $grade
     *           combined severity of all the DP's detections, with maybe some magic
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Datapoint::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string explanation = 1;</code>
     * @return string
     */
    public function getExplanation()
    {
        return $this->explanation;
    }

    /**
     * Generated from protobuf field <code>string explanation = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setExplanation($var)
    {
        GPBUtil::checkString($var, True);
        $this->explanation = $var;

        return $this;
    }

    /**
     * combined severity of all the DP's detections, with maybe some magic
     *
     * Generated from protobuf field <code>.proto.Grade grade = 2;</code>
     * @return int
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     * combined severity of all the DP's detections, with maybe some magic
     *
     * Generated from protobuf field <code>.proto.Grade grade = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGrade($var)
    {
        GPBUtil::checkEnum($var, \Proto\Grade::class);
        $this->grade = $var;

        return $this;
    }

}

