<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Datapoint.proto

namespace Proto;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>proto.Reply</code>
 */
class Reply extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string message = 1;</code>
     */
    private $message = '';

    public function __construct()
    {
        \GPBMetadata\Datapoint::initOnce();
        parent::__construct();
    }

    /**
     * <code>string message = 1;</code>
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * <code>string message = 1;</code>
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;
    }

}

