<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Datapoint.proto

namespace Proto\Agent;

/**
 * Protobuf type <code>proto.Agent.Type</code>
 */
class Type
{
    /**
     * Mozilla
     *
     * Generated from protobuf enum <code>BROWSER = 0;</code>
     */
    const BROWSER = 0;
    /**
     * google, baidu (low severity), Fakefox (high)
     *
     * Generated from protobuf enum <code>BOT = 1;</code>
     */
    const BOT = 1;
    /**
     * nmap
     *
     * Generated from protobuf enum <code>SCANNER = 2;</code>
     */
    const SCANNER = 2;
    /**
     * curl, wget, empty User-Agent
     *
     * Generated from protobuf enum <code>SCRIPT = 3;</code>
     */
    const SCRIPT = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Proto\Agent_Type::class);

